package it.rialtlas.healthmonitor.swagger.model;

/*
 * DataFlow API
 * Some custom description of API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@datagrafservizi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * DataFlowApiDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-04-11T09:45:08.986Z")
public class DataFlowApiDto {
    @SerializedName("codice_fiscale")
    private String codiceFiscale = null;

    @SerializedName("cognome")
    private String cognome = null;

    @SerializedName("docs_id")
    private List<Long> docsId = null;

    @SerializedName("nome")
    private String nome = null;

    @SerializedName("user_id")
    private String userId = null;

    @SerializedName("workFlow_id")
    private String workFlowId = null;

    public DataFlowApiDto codiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
        return this;
    }

    /**
     * Get codiceFiscale
     * @return codiceFiscale
     **/
    @ApiModelProperty(value = "")
    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    public void setCodiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }

    public DataFlowApiDto cognome(String cognome) {
        this.cognome = cognome;
        return this;
    }

    /**
     * Get cognome
     * @return cognome
     **/
    @ApiModelProperty(value = "")
    public String getCognome() {
        return cognome;
    }

    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    public DataFlowApiDto docsId(List<Long> docsId) {
        this.docsId = docsId;
        return this;
    }

    public DataFlowApiDto addDocsIdItem(Long docsIdItem) {
        if (this.docsId == null) {
            this.docsId = new ArrayList<Long>();
        }
        this.docsId.add(docsIdItem);
        return this;
    }

    /**
     * Get docsId
     * @return docsId
     **/
    @ApiModelProperty(value = "")
    public List<Long> getDocsId() {
        return docsId;
    }

    public void setDocsId(List<Long> docsId) {
        this.docsId = docsId;
    }

    public DataFlowApiDto nome(String nome) {
        this.nome = nome;
        return this;
    }

    /**
     * Get nome
     * @return nome
     **/
    @ApiModelProperty(value = "")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public DataFlowApiDto userId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     * @return userId
     **/
    @ApiModelProperty(value = "")
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public DataFlowApiDto workFlowId(String workFlowId) {
        this.workFlowId = workFlowId;
        return this;
    }

    /**
     * Get workFlowId
     * @return workFlowId
     **/
    @ApiModelProperty(value = "")
    public String getWorkFlowId() {
        return workFlowId;
    }

    public void setWorkFlowId(String workFlowId) {
        this.workFlowId = workFlowId;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DataFlowApiDto dataFlowApiDto = (DataFlowApiDto) o;
        return Objects.equals(this.codiceFiscale, dataFlowApiDto.codiceFiscale) &&
                Objects.equals(this.cognome, dataFlowApiDto.cognome) &&
                Objects.equals(this.docsId, dataFlowApiDto.docsId) &&
                Objects.equals(this.nome, dataFlowApiDto.nome) &&
                Objects.equals(this.userId, dataFlowApiDto.userId) &&
                Objects.equals(this.workFlowId, dataFlowApiDto.workFlowId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(codiceFiscale, cognome, docsId, nome, userId, workFlowId);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DataFlowApiDto {\n");

        sb.append("    codiceFiscale: ").append(toIndentedString(codiceFiscale)).append("\n");
        sb.append("    cognome: ").append(toIndentedString(cognome)).append("\n");
        sb.append("    docsId: ").append(toIndentedString(docsId)).append("\n");
        sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    workFlowId: ").append(toIndentedString(workFlowId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

